### ISSUE TITLE
Simplex algorithm magic code.

### ISSUE THREAD

**Issue by sxysxy** [RyanBernX/math#6]
See http://uoj.ac/problem/179
Simplex algorithm magic code template.
Languages c, c++(11), pascal, python2.7/3, Java7/8 are provided.

**Comment by RyanBernX** [comment]
Suggestions:
- MATLAB should also be provided.
- Why not open a simplex method course in the group  this Sunday? taroxd and Violacea may be interested in it.
- If interested, it's recommended to investigate other methods such as ADMM, inner-point method, etc. to solve LP.
